### ISSUE TITLE
The site is down. 

### ISSUE THREAD

**Issue by ctkqiang** [shadowoff09/lucifer-quotes#2]

**Comment by shadowoff09** [comment]
## New Website

[https://lucifer-quotes.vercel.app/](https://lucifer-quotes.vercel.app/)

## And the respective endpoints

### `GET /api/quotes`
Get a random quote in this format:

> [https://lucifer-quotes.vercel.app/api/quotes](https://lucifer-quotes.vercel.app/api/quotes)

### `GET /api/quotes/{number}`

Returns an array with `{number}` quotes e.g. `GET /api/quotes/5`.

> [https://lucifer-quotes.vercel.app/api/quotes/5](https://lucifer-quotes.vercel.app/api/quotes/5)

Thanks for the feedback!
